version: "3.8"

# build inditas
# docker-compose -f /PATH/docker-base/docker-compose.yml build --no-cache
# image belemaszas
# docker run --rm -it icellmobilsoft/base /bin/bash
# image inditasa
# docker run --rm icellmobilsoft/base
# label-ek ellenorzese
# docker inspect icellmobilsoft/base:1.0.0 | jq -r '.[0].Config.Labels'

services:

  # icellmobilsoft/base image release
  base-release:
    build:
      context: .
      dockerfile: dockerfile/bases/base/Dockerfile
      args:
        BASE_IMAGE: $BASE_IMAGE
    image: $DOCKER_IMAGE_BASE

  # icellmobilsoft/alpinebase image release
  alpinebase-release:
    build:
      context: .
      dockerfile: dockerfile/bases/alpinebase/Dockerfile
      args:
        ALPINE_BASE_IMAGE: $ALPINE_BASE_IMAGE
    image: $DOCKER_IMAGE_ALPINE_BASE

  # icellmobilsoft/curl image release
  curl-release:
    build:
      context: .
      dockerfile: dockerfile/bases/curl/Dockerfile
      args:
        BASE_IMAGE: $DOCKER_IMAGE_BASE
    image: $DOCKER_IMAGE_CURL

  # icellmobilsoft/java11jre
  java11jre-release:
    build:
      context: .
      dockerfile: dockerfile/bases/javajre/Dockerfile
      args:
        BASE_IMAGE: $DOCKER_IMAGE_CURL
        JRE_TEMURIN_IMAGE: $JRE_11_TEMURIN_IMAGE
    image: $DOCKER_IMAGE_JAVA11JRE

  # icellmobilsoft/java17jre
  java17jre-release:
    build:
      context: .
      dockerfile: dockerfile/bases/javajre/Dockerfile
      args:
        BASE_IMAGE: $DOCKER_IMAGE_CURL
        JRE_TEMURIN_IMAGE: $JRE_17_TEMURIN_IMAGE
    image: $DOCKER_IMAGE_JAVA17JRE

  # icellmobilsoft/liquibase
  liquibase-release:
    build:
      context: .
      dockerfile: dockerfile/bases/liquibase/Dockerfile
      args:
        BASE_IMAGE: $DOCKER_IMAGE_JAVA11JRE
        LIQUIBASE_IMAGE: $LIQUIBASE_IMAGE
    image: $DOCKER_IMAGE_LIQUIBASE
