name: Docker release

on:
  workflow_dispatch:
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Comment for release'
        # Default value if no value is explicitly provided
        default: 'Start release from WEB UI'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v3
        with:
          # Ne az a user legyen aki a workflow-ot inditotta
          token: ${{ secrets.GH_TOKEN_TECHUSER_JAVA }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/isbang/compose-action
      - name: Run docker-compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
#        env:
#          IMAGE_NAME: hello-world
